extraArgs:
  provider: github
  # UPDATE THIS with your domain or ELB URL
  redirect-url: "https://datavisyn-demo.duckdns.org/oauth2/callback"
  # Set to "true" when using HTTPS, "false" for HTTP
  cookie-secure: "true"

ingress:
  enabled: true
  className: nginx
  path: /oauth2
  pathType: Prefix
  hosts:
    - datavisyn-demo.duckdns.org
  
  tls:
    - secretName: webapp-tls
      hosts:
        - datavisyn-demo.duckdns.org